name:                hadvent
version:             0.1.0.0
github:              "erykciepiela/advent"
license:             BSD3
author:              "Eryk Ciepiela"
maintainer:          "eryk.ciepiela.dev@gmail.com"
copyright:           "2019 Eryk Ciepiela"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/advent2019#readme>

default-extensions:
- OverloadedStrings
# - OverloadedLists
- ScopedTypeVariables
- DerivingVia
- StandaloneDeriving
- TupleSections
- DeriveFunctor
- LambdaCase
- BangPatterns

dependencies:
- base >= 4.7 && < 5
- http-client -any
- bytestring -any
- HTTP -any
- http-client-tls -any
- http-conduit -any
- directory -any
- split -any
- text -any
- containers -any
- mtl -any
- Hclip -any
- Data-Angle -any
- comonad -any
- listsafe -any
- cryptohash-sha256 -any
- parsec -any
- lattices -any
- pomaps -any
- either -any
- distributive

library:
  source-dirs: src

executables:
  2018-1:
    main:                Main.hs
    source-dirs:         "2018/1"
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hadvent
  2018-2:
    main:                Main.hs
    source-dirs:         "2018/2"
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hadvent
  2019-1:
    main:                Main.hs
    source-dirs:         "2019/1"
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hadvent
  2019-2:
    main:                Main.hs
    source-dirs:         "2019/2"
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hadvent
  2019-3:
    main:                Main.hs
    source-dirs:         "2019/3"
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hadvent
  2019-4:
    main:                Main.hs
    source-dirs:         "2019/4"
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hadvent
  2019-5:
    main:                Main.hs
    source-dirs:         "2019/5"
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hadvent
  2019-6:
    main:                Main.hs
    source-dirs:         "2019/6"
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hadvent
  2019-7:
    main:                Main.hs
    source-dirs:         "2019/7"
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hadvent
  2019-8:
    main:                Main.hs
    source-dirs:         "2019/8"
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hadvent
  2019-9:
    main:                Main.hs
    source-dirs:         "2019/9"
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hadvent
  2019-10:
    main:                Main.hs
    source-dirs:         "2019/10"
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hadvent
  2019-11:
    main:                Main.hs
    source-dirs:         "2019/11"
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hadvent
  2019-12:
    main:                Main.hs
    source-dirs:         "2019/12"
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hadvent
  2019-13:
    main:                Main.hs
    source-dirs:         "2019/13"
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hadvent
  2019-14:
    main:                Main.hs
    source-dirs:         "2019/14"
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hadvent
  2019-15:
    main:                Main.hs
    source-dirs:         "2019/15"
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hadvent
  2019-16:
    main:                Main.hs
    source-dirs:         "2019/16"
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hadvent
  2019-17:
    main:                Main.hs
    source-dirs:         "2019/17"
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hadvent
  2019-18:
    main:                Main.hs
    source-dirs:         "2019/18"
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hadvent
  2020-1:
    main:                Main.hs
    source-dirs:         "2020/1"
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hadvent
  2020-2:
    main:                Main.hs
    source-dirs:         "2020/2"
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hadvent
  2020-3:
    main:                Main.hs
    source-dirs:         "2020/3"
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hadvent
  2020-4:
    main:                Main.hs
    source-dirs:         "2020/4"
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hadvent
  2020-5:
    main:                Main.hs
    source-dirs:         "2020/5"
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hadvent
  2020-6:
    main:                Main.hs
    source-dirs:         "2020/6"
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hadvent
  2020-7:
    main:                Main.hs
    source-dirs:         "2020/7"
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hadvent
  2020-8:
    main:                Main.hs
    source-dirs:         "2020/8"
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hadvent
  2020-9:
    main:                Main.hs
    source-dirs:         "2020/9"
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hadvent
  2020-10:
    main:                Main.hs
    source-dirs:         "2020/10"
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hadvent
  2020-11:
    main:                Main.hs
    source-dirs:         "2020/11"
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hadvent
  2020-12:
    main:                Main.hs
    source-dirs:         "2020/12"
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hadvent
  2020-13:
    main:                Main.hs
    source-dirs:         "2020/13"
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hadvent
  2020-14:
    main:                Main.hs
    source-dirs:         "2020/14"
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hadvent
  2020-15:
    main:                Main.hs
    source-dirs:         "2020/15"
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hadvent
  2020-16:
    main:                Main.hs
    source-dirs:         "2020/16"
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hadvent
  # 2020-17:
  #   main:                Main.hs
  #   source-dirs:         "2020/17"
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - hadvent
  2020-18:
    main:                Main.hs
    source-dirs:         "2020/18"
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hadvent
  2020-19:
    main:                Main.hs
    source-dirs:         "2020/19"
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hadvent
  2020-20:
    main:                Main.hs
    source-dirs:         "2020/20"
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hadvent
  2020-21:
    main:                Main.hs
    source-dirs:         "2020/21"
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hadvent

tests:
  advent-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent
