name:                hadvent
version:             0.1.0.0
github:              "erykciepiela/advent"
license:             BSD3
author:              "Eryk Ciepiela"
maintainer:          "eryk.ciepiela.dev@gmail.com"
copyright:           "2019 Eryk Ciepiela"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/advent2019#readme>

default-extensions: 
- OverloadedStrings
- OverloadedLists
- ScopedTypeVariables

dependencies:
- base >= 4.7 && < 5
- http-client -any
- bytestring -any
- HTTP -any
- http-client-tls -any
- http-conduit -any
- directory -any
- split -any
- text -any

library:
  source-dirs: src

executables:
  2018-1:
    main:                Main.hs
    source-dirs:         "2018/1"
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hadvent
  2018-2:
    main:                Main.hs
    source-dirs:         "2018/2"
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hadvent
  2019-1:
    main:                Main.hs
    source-dirs:         "2019/1"
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hadvent
  2019-2:
    main:                Main.hs
    source-dirs:         "2019/2"
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hadvent

tests:
  advent-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent
